FROM node:20-alpine

WORKDIR /usr/gitmesh/frontend

RUN npm install -g pnpm

COPY pnpm-lock.yaml package.json ./
RUN pnpm install --frozen-lockfile

COPY .browserslistrc .eslintrc.js babel.config.js postcss.config.js tailwind.config.js vite.config.js tsconfig.json index.html ./
COPY ./public ./public
COPY ./src ./src