FROM node:20-alpine

RUN apk add --update --no-cache bash python3 build-base micro git ncurses && ln -sf python3 /usr/bin/python && python3 -m ensurepip && pip3 install --no-cache --upgrade pip setuptools

WORKDIR /usr/gitmesh/app

RUN git clone https://github.com/LF-Decentralized-Trust-labs/gitmesh.git && cd gitmesh && (cd services/scripts && ./install_all_packages.sh) && (cd backend && npm ci)

WORKDIR /usr/gitmesh/app/gitmesh