FROM node:20-alpine

# Install bash and build dependencies
RUN apk add --update --no-cache bash python3 build-base

WORKDIR /usr/gitmesh/app

RUN npm install -g pnpm

COPY ./services/scripts ./services/scripts
COPY ./services/libs/ ./services/libs/
RUN cd services/scripts && ./install_lib_packages.sh

COPY ./services/apps/search_sync_worker/package.json ./services/apps/search_sync_worker/pnpm-lock.yaml ./services/apps/search_sync_worker/tsconfig.json  ./services/apps/search_sync_worker/
COPY ./services/apps/search_sync_worker/config ./services/apps/search_sync_worker/config
COPY ./services/apps/search_sync_worker/src ./services/apps/search_sync_worker/src

RUN cd services/apps/search_sync_worker && pnpm install --frozen-lockfile
